title: Federico Mazzoni # your name (or website title) here
logo: "/images/photo_f.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  Hi! I work at Domotz, integrating new AI solutions within the company's framework. My background is in Data Science, and for one year and a half I've been a PhD Fellow in AI at the University of Pisa, before realizing my personality was better aligned with the industry.
  <br><br>
  On this page, you'll find a compilation of the projects I've undertaken over the years, whereas <a href="https://flowcv.com/resume/mvwcmvh8l1">here</a> you can find my up-to-date CV.
  <br><br>
  If you want to get in contact, feel free to <a href="mailto:mazzoni.federico1@gmail.com">drop an email</a> or add me on <a href="https://www.linkedin.com/in/federico-mazzoni-728953247/">LinkedIn</a>. I always love going out of my comfort zone and learning something new.
  </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
